import { DialogueDto } from 'src/dtos/dialog.dto';
import { FormDto } from 'src/dtos/form.dto';

/**
 * Builds a prompt for the AI to generate Unity C# ScriptableObject classes
 * from a JSON response.
 *
 * @param jsonData - JSON string previously generated by the AI
 * @returns A string prompt ready to send to the AI model
 *
 * The AI will map top-level JSON objects to ScriptableObjects, nested objects
 * to appropriate C# classes, and output only valid Unity C# code.
 */
export function buildScriptableObjectPrompt(jsonData: FormDto) {
  return `
          Generate Unity C# ScriptableObject classes using the JSON below as the source of data.
          - Map each top-level JSON object to a ScriptableObject class.
          - Map nested objects/arrays to appropriate C# classes.
          - Use [CreateAssetMenu] for each ScriptableObject.
          - Ensure class and property names match the JSON keys (PascalCase recommended).
          - Do not include MonoBehaviour or Editor code.
          - Output only valid C# code.

          JSON Source:
          ${JSON.stringify(jsonData, null, 2)}
          `;
}

/**
 * Builds a prompt for the AI to generate a structured JSON response
 * based on user input from a form.
 *
 * @param formData - An object containing user input for NPC and Quest data
 * @returns A string prompt ready to send to the AI model
 *
 * The AI will return JSON strictly following the response schema defined
 * in the system instruction.
 */
export function buildJsonPrompt(formData: FormDto) {
  const { name, role, personality } = formData.npc;
  const { title, description } = formData.quest;
  return `
    Generate a structured JSON response strictly following the response schema.
    use the net setting in your response as this is the user request for this
    properties to be part of the response:
    
    NPC Data:
    - Name: ${name}
    - Role: ${role}
    - Personality: ${personality}

    Quest Data:
    - Title: ${title}
    - Description: ${description}
  `;
}
